version: '3.8'

services:
  mariadb:
    image: mariadb:11.0
    container_name: order-food-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./migrations:/migrations
    networks:
      - order-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: order-food-api
    env_file:
      - .env
    depends_on:
      - mariadb
    networks:
      - order-network
    ports:
      - "${PORT}:8080"
    command: ["sh", "/app/start.sh"]

volumes:
  mariadb_data:
    driver: local

networks:
  order-network:
    driver: bridge
